import {StyleSheet} from 'react-native';
import Colors from '../../assets/colors/Colors';

const styles = StyleSheet.create({
  home_View: {
    width: '100%',
    backgroundColor: Colors.DARK_PURPAL,
    flex: 1,
  },
  home_Filter_View: {
    flexDirection: 'row',
    margin: 15,
  },
  home_Filter_text: {
    color: Colors.WHITE,
    alignSelf: 'center',
    fontFamily: 'Sora-Regular',
    fontSize: 12,
  },
  home_Filter_Icon: {
    width: 18,
    height: 18,
    justifyContent: 'center',
    marginTop: 2,
  },
  home_Folder_Image: {
    width: '33.3%',
    height: 140,
    marginBottom: 30,
    marginLeft: '2%',
  },
  home_Folder_Image_Next: {
    width: '33.3%',
    height: 140,
    marginBottom: '0.5%',
    marginLeft: '0.5%',
  },

  home_Folder_Text_View: {
    position: 'absolute',
    height: 35,
    backgroundColor: '#00000077',
    width: '100%',
    bottom: 0,
    flexDirection: 'row',
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
  },

  home_Folder_Text: {
    width: '26%',
    backgroundColor: Colors.LIGHT_PURPAL,
    borderBottomRightRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  home_Folder_Text2: {
    width: '26%',
    borderBottomRightRadius: 15,
    justifyContent: 'center',
  },
  Menu_Text: {
    fontSize: 16,
    fontFamily: 'Sora-Regular',
    color: Colors.WHITE,
  },
  Menu_Text_Container: {
    justifyContent: 'center',
    marginVertical: -5,
    paddingLeft: 10,
    // width:,..
    // backgroundColor: 'red',
    borderRadius: 12,
  },
  Menu_Header: {
    color: Colors.WHITE,
    fontSize: 12,
    fontWeight: '400',
    marginTop: 15,
    marginBottom: 10,
    marginLeft: '10%',
    fontFamily: 'Sora-Regular',
  },
  menu: {
    marginTop: '10%',
    width: 250,
    marginRight: 100,
    backgroundColor: Colors.PURPAL,
    borderRadius: 12,
    borderColor: Colors.LIGHT_PURPAL,
    borderWidth: 1,
  },
  Password_View: {
    flex: 1,
    backgroundColor: Colors.DARK_PURPAL,
  },
  text_view: {
    width: '90%',
    marginBottom: '5%',
    paddingTop: '5%',
    alignSelf: 'center',
  },
  back_Btn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  back_Btn_Image: {width: 30, height: 30, alignSelf: 'center'},
  Create_Password_text: {
    fontFamily: 'Sora-Regular',
    fontSize: 24,
    fontWeight: '400',
    color: Colors.WHITE,
    alignSelf: 'center',
  },
  Enter_text: {
    fontFamily: 'Sora-Regular',
    fontWeight: '200',
    fontSize: 14,
    color: Colors.WHITE,
    lineHeight: 22,
    marginTop: 5,
    marginLeft: '10%',
  },
  locker_view: {
    width: '80%',
    alignSelf: 'center',
    alignItems: 'center',
    marginVertical: '3%',
  },
  locker_Image: {
    width: '80%',
    height: 150,
    marginLeft: '25%',
  },
  otp_View: {
    width: '80%',
    height: 80,
    alignSelf: 'center',
    marginVertical: '5%',
  },
  underlineStyleBase: {
    width: 60,
    height: 60,
    borderWidth: 1,
    borderRadius: 13,
    borderBottomWidth: 1,
    color: Colors.WHITE,
    fontSize: 29,
    fontFamily: 'Sora-Regular',
  },
  underlineStyleHighLighted: {
    borderColor: Colors.LIGHT_PURPAL,
  },
  error_View: {
    width: '80%',
    backgroundColor: Colors.WHITE,
    borderRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  error_Text: {
    color: Colors.REd,
    fontFamily: 'Sora-Regular',
    textAlign: 'center',
    marginVertical: '3%',
    justifyContent: 'center',
  },
  btn_View: {
    alignSelf: 'center',
    width: '100%',
    marginBottom: '5%',
  },
  finger_Print: {
    alignItems: 'center',
    marginVertical: '5%',
  },
  finger_Print_Text: {color: Colors.SKY_BLUE, fontFamily: 'Sora-Regular'},
  lock_View: {flex: 1, backgroundColor: Colors.DARK_PURPAL},
  lock_Img_View: {width: '100%', position: 'absolute', top: 0, bottom: 0},
  lock_Image_View: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lock_Private_Text: {
    fontSize: 18,
    fontFamily: 'Sora-Regular',
    fontWeight: '600',
    color: Colors.WHITE,
    marginBottom: 15,
  },
  lock_Text: {
    fontSize: 14,
    fontFamily: 'Sora-Regular',
    fontWeight: '400',
    color: Colors.WHITE,
    marginBottom: 30,
    width: '80%',
    textAlign: 'center',
  },
  image_headerView_Gallery: {
    backgroundColor: Colors.PURPAL,
    height: 70,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    
    
    
  },
  image_NameText_Gallery: {
    color: Colors.WHITE,
    alignSelf: 'center',
    fontFamily: 'Sora-Regular',
    fontSize: 20,
    fontWeight: '600',
  },
  folderText_Name_PrivateScreen: {
    color: Colors.WHITE,
    marginLeft: 7,
    fontFamily: 'Sora-Regular',
    fontSize: 12,
  },
  folderText_Counter_PrivateScreen: {
    textAlign: 'center',
    color: Colors.WHITE,
    fontFamily: 'Sora-Regular',
    fontSize: 12,
  },
  flatlist_counterWrap_PrivateScreen: {
    justifyContent: 'flex-start',
    width: '92%',
    marginTop: 10,
  },
  button_View_PrivateScreen: {
    width: '100%',
    height: 100,
    backgroundColor: Colors.DARK_PURPAL,
    justifyContent: 'center',
  },
  modal_View_PrivateScree: {
    position: 'absolute',
    bottom: 0,
    height: '50%',
    backgroundColor: Colors.X_LIGHT_PURPAL,
    borderTopRightRadius: 70,
    borderTopLeftRadius: 70,
    width: '100%',
    justifyContent: 'space-evenly',
  },
  modal_album_text_PrivateScreen: {
    color: Colors.WHITE,
    alignSelf: 'center',
    fontFamily: 'Sora-Regular',
    fontSize: 18,
    fontWeight: '600',
  },
});
export default styles;
